export enum ApiResources {
    User = "users/user",
    Users = "users",
    Login = "users/login",
    Logout = "users/logout",
    Register = "users/user",
    Coupons = "coupons",
    Coupon = "coupons/coupon",
    Products = "products",
    Cart = "carts",
    MoreQuantity = "carts/moreQuantity",
    LessQuantity = "carts/lessQuantity",
    Redeem = "carts/coupon",
    Unredeem="carts/couponFree",
    AddToCart="products/cart",
    Checkout="carts/finalCart",
    Orders = "users/orders",
    Order = "users/orders",
    Menu = "menu/",
    NewComment = "products/comment",
    Booking = "bookings/"
}